### ISSUE TITLE
Double Record 

### ISSUE THREAD

**Issue by Paul-Riedel** [vimes1984/video_sitemap#4]
Hi,

I found a double record in the file. It seems that the first record comes twice:

<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="http://pauls-kochstube.de/wp-content/plugins/youtube-video-sitemap-generator/video-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">

 <url>
 <loc>http://pauls-kochstube.de/?p=832</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v//video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi//hqdefault.jpg/video:thumbnail_loc
  video:titleMeine Playlist auf YouTube/video:title
  video:descriptionIm 2015 starte ich meine Edition Eins und lade Sie ein, in mein Kochkunst teilzuhaben. In diese Playlist erfahren Sie mehr darüber./video:description
  video:publication_date2015-03-08T20:24:19+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=1042</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/EjwrSg64L1A/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/EjwrSg64L1A/hqdefault.jpg/video:thumbnail_loc
  video:titleEier kochen richtig gemacht/video:title
  video:descriptionSie dachten, dass das perfekte gekochtes Ei leicht zu kochen wäre? Ich zeige wie das richtig geht./video:description
  video:publication_date2015-04-04T11:20:23+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=1036</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/ruyiEMFVREc/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/ruyiEMFVREc/hqdefault.jpg/video:thumbnail_loc
  video:titleKartoffelbrot/video:title
  video:descriptionUnser tägliches Brot muss nicht immer gleich sein. Etwas Kartoffel und einige Viktualien und prompt ist das Frühstück viel interessanter als sonst./video:description
  video:publication_date2015-04-04T11:08:17+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=1034</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/bMUbRTODOOU/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/bMUbRTODOOU/hqdefault.jpg/video:thumbnail_loc
  video:titleBrotaufstrich Mediterraner Art/video:title
  video:descriptionMeine Variante ist weniger Fett und schont die Pölsterchen. Probieren Sie auch mit Knoblauch anstatt der Knoblauchpulver. Schmeckt fantastisch./video:description
  video:publication_date2015-04-04T11:02:11+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=907</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/EjwrSg64L1A/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/EjwrSg64L1A/hqdefault.jpg/video:thumbnail_loc
  video:titleEierkochen richtig gemacht/video:title
  video:descriptionEierkochen richtig gemacht/video:description
  video:publication_date2015-03-31T16:40:48+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=859</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/q0DXVJ0L5eE/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/q0DXVJ0L5eE/hqdefault.jpg/video:thumbnail_loc
  video:titleSchokokekse nach Oma Erna/video:title
  video:descriptionEinfacher geht es kaum. Das ist ein Rezept für Schokokekse aus den Kochbuch meiner Oma Erna./video:description
  video:publication_date2015-03-13T14:21:38+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=832</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/videoseries/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/videoseries/hqdefault.jpg/video:thumbnail_loc
  video:titleMeine Playlist auf YouTube/video:title
  video:descriptionIm 2015 starte ich meine Edition Eins und lade Sie ein, in mein Kochkunst teilzuhaben. In diese Playlist erfahren Sie mehr darüber./video:description
  video:publication_date2015-03-08T20:24:19+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=771</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/L_AVdMO7KgU/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/L_AVdMO7KgU/hqdefault.jpg/video:thumbnail_loc
  video:titlePaul in 1 Minute/video:title
  video:descriptionProgramm Intro in eine Minute erzähle ich hier alles über mein YouTube Kanal./video:description
  video:publication_date2015-03-08T12:22:29+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=769</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/GXQHJHdnNBs/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/GXQHJHdnNBs/hqdefault.jpg/video:thumbnail_loc
  video:titleAubergine Kürbis Brotaufstrich/video:title
  video:descriptionWenn Ihren Mann und Ihre Kindern keine Gemüse essen mögen, machen Sie wie ich, werden Sie erfinderisch. Meine Brotaufstriche sind auf jeden Fall gerne willkommen./video:description
  video:publication_date2015-03-08T12:18:17+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=473</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/9-Qvz1_5bSg/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/9-Qvz1_5bSg/hqdefault.jpg/video:thumbnail_loc
  video:titleRosa Wölkchen Frosting/video:title
  video:descriptionWie wäre es, mit einen neuen Frosting um Ihren Muffin oder Cup-Cake noch attraktiver zu machen? Hier ist einfach erklärt, inklusive Rezept, wie man ein Rosa Frosting selbst macht./video:description
  video:publication_date2015-02-08T16:07:26+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=372</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/8toSMvPmjOM/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/8toSMvPmjOM/hqdefault.jpg/video:thumbnail_loc
  video:titleValentine Cookies/video:title
  video:descriptionMit Freude am Backen. Anleitung zu mein Rezept für ein sowohl schmackhaften als auch gute aussehende Cookie. Machen Sie aus Ihren Valentins Frühstück ein Ereigniss./video:description
  video:publication_date2015-02-02T12:07:34+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=368</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/y5VaXwtDAvg/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/y5VaXwtDAvg/hqdefault.jpg/video:thumbnail_loc
  video:titleBrotaufstrich Aubergine nach Türkischer Art/video:title
  video:descriptionMit Freude am Kochen. Anleitung zu mein Rezept um eine exotischer Brotaufstrich. Einfach und schnell für den perfekten Frühstück vorbereiten./video:description
  video:publication_date2015-02-01T18:31:21+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=363</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/O2Xks2AJ4b0/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/O2Xks2AJ4b0/hqdefault.jpg/video:thumbnail_loc
  video:titleKartoffel Gratin leicht gemacht/video:title
  video:descriptionMit Freude am Kochen. Anleitung zu mein Rezept um eine schmackhaften Kartoffelauflauf. Einfach und schnell für den Abend kochen./video:description
  video:publication_date2015-02-01T15:09:58+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=304</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/yLzsbnx-E_Q/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/yLzsbnx-E_Q/hqdefault.jpg/video:thumbnail_loc
  video:titleZucchini Brotaufstrich/video:title
  video:descriptionMeine vegetarische Rezepte sind sowohl gesund als auch leicht erklärt. Auch für Diäten geeignet./video:description
  video:publication_date2015-01-29T12:41:31+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=284</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/8GaShOD0ao4/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/8GaShOD0ao4/hqdefault.jpg/video:thumbnail_loc
  video:titleHimmel Frosting/video:title
  video:descriptionMuffings, Cupcakes oder Cake-Pops müssen nicht trocken und farblos sein, wenn Sie das richtige Frosting Rezept haben. Mit meine Videoanleitung für Topping, schafen Sie Freunde und Gäste zu beeindrucken./video:description
  video:publication_date2015-01-28T12:59:20+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=281</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/8GaShOD0ao4/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/8GaShOD0ao4/hqdefault.jpg/video:thumbnail_loc
  video:titleVanille Muffin/video:title
  video:descriptionMit Freude am backen. Anleitung zu mein Rezept um eine schöne Muffin zu backen. Rezept zum ausdrucken ist auch vorhanden./video:description
  video:publication_date2015-01-28T12:55:38+00:00/video:publication_date
 /video:video
 </url>
 <url>
 <loc>http://pauls-kochstube.de/?p=243</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/FTJl1g8ELQA/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/FTJl1g8ELQA/hqdefault.jpg/video:thumbnail_loc
  video:titleKäse Cracker/video:title
  video:descriptionKäse craker Videoanleitung mit den brasilianischen Flair von Paul Riedel. Ausdruckbare Anleitung auch verfügbar./video:description
  video:publication_date2015-01-26T18:41:12+00:00/video:publication_date
 /video:video
 </url>
</urlset>

Cheers

Paul

**Comment by vimes1984** [comment]
yes Paul you have the video on two seperate pages... : 
http://pauls-kochstube.de/?p=907
AND 
http://pauls-kochstube.de/?p=1042

...

**Comment by Paul-Riedel** [comment]
Sorry, my mistake!
