### ISSUE TITLE
So I Tried To Create A Video Sitemap & This Happened...

### ISSUE THREAD

**Issue by urbanwidemedia** [vimes1984/video_sitemap#5]
http://i817.photobucket.com/albums/zz94/youngraleigh/Work%20Photos/VideoSitemapIssuesScreenshot20150423_zpslnlu3nuy.png~original

Any help with this issue will be appreciated.

**Comment by vimes1984** [comment]
I've just released a new version see if that fixes it for you... 
Ver 1.2.3

**Comment by urbanwidemedia** [comment]
Just updated it & it seems to work for now...

**Comment by vimes1984** [comment]
A thank you would be nice mate....
