### ISSUE TITLE
Video Sitemap Plugin - Subscribers

### ISSUE THREAD

**Issue by radforms** [vimes1984/video_sitemap#6]
Subscribers to a blog can see the link for this plugin in their dashboard.  Should really be for admins or editors only

**Comment by vimes1984** [comment]
yeah it should be reallly..

**Comment by vimes1984** [comment]
version 1.2.4 should have fixed that...

**Comment by radforms** [comment]
Hi Vimes - I installed 1.2.4 and subscribers can still see the Video Sitemap option on their dashboard

**Comment by vimes1984** [comment]
ok I'll open it up in the morn and see why...

**Comment by vimes1984** [comment]
srry about that used the wrong function. Version 1.2.6 should have fixed it :D

**Comment by radforms** [comment]
cheers mate, will test soon and let you know

**Comment by radforms** [comment]
Hi @vimes1984  tested now logged in as subscriber and has disappeared now from their dashboard.  Thanks heaps for that :)
